version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: funeral_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kaborehakim@1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgresql://postgres:Kaborehakim%401@db:5432/funeral_management
    depends_on:
      - db

volumes:
  db_data:
