import bcrypt from 'bcryptjs'; import { asyncHandler, AppError } from '../utils/errors.js'; import { signToken } from '../middleware/auth.js'; import { query } from '../config/db.js'; import { validEmail, validPhone, validStrongPassword } from '../utils/validation.js';
export const users=asyncHandler(async(req,res)=>{ const role = req.query.role ? String(req.query.role).trim().toUpperCase() : undefined; const params:any[] = []; let sql = 'select id,role,full_name,email,phone,status,created_at,organizer_identifier from users where status != $1 order by created_at desc'; params.push('DELETED'); if (role && ['SUPER_ADMIN','ORGANIZER','FAMILY_MEMBER'].includes(role)) { sql = 'select id,role,full_name,email,phone,status,created_at,organizer_identifier from users where role=$1 and status != $2 order by created_at desc'; params.unshift(role); } const {rows}=await query(sql, params); res.json(rows); });
export const createSuperAdmin=asyncHandler(async (req,res)=>{ const fullName = String(req.body.fullName || '').trim(); const email = req.body.email ? String(req.body.email).trim().toLowerCase() : null; const phone = req.body.phone ? String(req.body.phone).trim() : null; const password = String(req.body.password || '');
 if (!fullName) throw new AppError(422, 'Full name is required'); if (!email && !phone) throw new AppError(422, 'Email or phone is required'); if (email && !validEmail(email)) throw new AppError(422, 'Invalid email'); if (phone && !validPhone(phone)) throw new AppError(422, 'Invalid phone number. Use international format, e.g. +233XXXXXXXXX'); if (!validStrongPassword(password)) throw new AppError(422, 'Password must be at least 8 characters and include uppercase, lowercase, number and symbol');
 const params:any[] = ['DELETED']; let existingSql = 'select id from users where status != $1'; if (email && phone) { existingSql += ' and (email=$2 or phone=$3)'; params.push(email, phone); } else if (email) { existingSql += ' and email=$2'; params.push(email); } else { existingSql += ' and phone=$2'; params.push(phone); }
 const existing = await query(existingSql, params); if (existing.rows[0]) throw new AppError(409, 'A user already exists with that email or phone');
 const hash = await bcrypt.hash(password, 12); const status = 'ACTIVE'; const emailVerified = !!email; const phoneVerified = !!phone;
 const { rows } = await query(
   `insert into users (role, full_name, email, phone, password_hash, email_verified, phone_verified, status)
    values ($1,$2,$3,$4,$5,$6,$7,$8)
    returning id, role, full_name, email, phone, status, created_at`,
   ['SUPER_ADMIN', fullName, email, phone, hash, emailVerified, phoneVerified, status]
 );
 res.status(201).json(rows[0]); });
export const userDetail=asyncHandler(async(req,res)=>{ const {id}=req.params; const {rows}=await query(`select u.id,u.role,u.full_name,u.email,u.phone,u.status,u.created_at,u.organizer_identifier,o.subscription_status from users u left join organizers o on o.user_id=u.id where u.id=$1 limit 1`,[id]); if(!rows[0]) return res.status(404).json({ message:'User not found' }); res.json(rows[0]); });
export const setStatus=asyncHandler(async(req,res)=>{ const {id}=req.params; const {status}=req.body; const {rows}=await query('update users set status=$1 where id=$2 returning id,status',[status,id]); res.json(rows[0]); });
export const deleteUser=asyncHandler(async(req,res)=>{ const {id}=req.params; if (req.user?.id === id) throw new AppError(403, 'You cannot delete your own account here'); const {rows}=await query('update users set status=$1,deleted_at=now() where id=$2 returning id,role,full_name,email,phone,status,deleted_at',['DELETED',id]); if(!rows[0]) return res.status(404).json({ message:'User not found' }); res.json(rows[0]); });
export const impersonateUser=asyncHandler(async(req,res)=>{ const {id}=req.params; const {rows}=await query('select u.id,u.role,u.full_name,u.email,u.phone,u.status,u.organizer_identifier,o.subscription_status from users u left join organizers o on o.user_id = u.id where u.id=$1 and u.status != $2 limit 1',[id,'DELETED']); const target = rows[0]; if(!target) return res.status(404).json({ message:'User not found or deleted' }); const user = { id: target.id, role: target.role, fullName: target.full_name, email: target.email, phone: target.phone, status: target.status, organizerIdentifier: target.organizer_identifier, subscriptionStatus: target.subscription_status }; const token = signToken({ id: target.id, role: target.role, status: target.status }); res.json({ token, user }); });
export const analytics=asyncHandler(async(req,res)=>{ const users=(await query('select role,count(*) from users where status != $1 group by role',['DELETED'])).rows; const totalUsersRow=(await query('select count(*) as count from users where status != $1',['DELETED'])).rows[0]; const payments=(await query('select status,coalesce(sum(amount),0) total,count(*) from payments group by status')).rows; const totalPaymentsRow=(await query('select count(*) as count from payments')).rows[0]; const totalPaidPaymentsRow=(await query('select count(*) as count from payments where status=$1',['PAID'])).rows[0]; const totalRevenueRow=(await query('select coalesce(sum(amount),0) as total from payments where status=$1',['PAID'])).rows[0]; const totalPendingPaymentsRow=(await query('select count(*) as count from payments where status=$1',['PENDING'])).rows[0]; const sessions=(await query('select status,count(*) from funeral_sessions group by status')).rows; const totalSessionsRow=(await query('select count(*) as count from funeral_sessions')).rows[0]; const totalActiveOrganizersRow=(await query('select count(*) as count from users where role=$1 and status = $2',['ORGANIZER','ACTIVE'])).rows[0]; const monthlyUserSignups=(await query(`select to_char(months.month, 'Mon YYYY') label, coalesce(u.count, 0) count from generate_series(date_trunc('month', now()) - interval '11 month', date_trunc('month', now()), interval '1 month') as months(month) left join (select date_trunc('month', created_at) as month, count(*) from users where status != 'DELETED' group by 1) u on u.month = months.month order by months.month`)).rows; const monthlyRevenue=(await query(`select to_char(months.month, 'Mon YYYY') label, coalesce(p.total, 0) total from generate_series(date_trunc('month', now()) - interval '11 month', date_trunc('month', now()), interval '1 month') as months(month) left join (select date_trunc('month', created_at) as month, sum(amount) as total from payments where status = 'PAID' group by 1) p on p.month = months.month order by months.month`)).rows; const monthlySessions=(await query(`select to_char(months.month, 'Mon YYYY') label, coalesce(s.count, 0) count from generate_series(date_trunc('month', now()) - interval '11 month', date_trunc('month', now()), interval '1 month') as months(month) left join (select date_trunc('month', created_at) as month, count(*) from funeral_sessions group by 1) s on s.month = months.month order by months.month`)).rows; res.json({ users, payments, sessions, totalUsers: Number(totalUsersRow.count), totalPayments: Number(totalPaymentsRow.count), totalPaidPayments: Number(totalPaidPaymentsRow.count), totalRevenue: Number(totalRevenueRow.total), totalPendingPayments: Number(totalPendingPaymentsRow.count), totalSessions: Number(totalSessionsRow.count), totalActiveOrganizers: Number(totalActiveOrganizersRow.count), monthlyUserSignups, monthlyRevenue, monthlySessions }); });
