create extension if not exists "uuid-ossp";
create type user_role as enum ('SUPER_ADMIN','ORGANIZER','FAMILY_MEMBER');
create type account_status as enum ('PENDING_PAYMENT','ACTIVE','SUSPENDED','DELETED');
create type payment_status as enum ('PENDING','PAID','FAILED','REFUNDED','CANCELLED');
create type session_status as enum ('PENDING','PLANNING','ACTIVE','COMPLETED','ARCHIVED');
create type request_status as enum ('PENDING','ACCEPTED','REJECTED','INVOICED','PAID','SESSION_CREATED');
create type donation_type as enum ('CASH','IN_KIND','MOMO');

create table users (id uuid primary key default uuid_generate_v4(), role user_role not null, full_name text not null, email text unique, phone text unique, password_hash text, email_verified boolean default false, phone_verified boolean default false, status account_status default 'PENDING_PAYMENT', last_login_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz, constraint email_format check (email is null or email ~* '^[^\s@]+@[^\s@]+\.[^\s@]{2,}$'));
create index idx_users_role on users(role); create index idx_users_status on users(status);
create table organizers (id uuid primary key default uuid_generate_v4(), user_id uuid unique not null references users(id) on delete cascade, organizer_identifier text unique not null, subscription_status text default 'INACTIVE', service_charge_percent numeric(5,2) default 10.00, created_at timestamptz default now());
create table family_members (id uuid primary key default uuid_generate_v4(), user_id uuid unique not null references users(id) on delete cascade, created_at timestamptz default now());
create table illiterate_family_records (id uuid primary key default uuid_generate_v4(), organizer_id uuid not null references organizers(id), full_name text not null, phone text, notes text, created_at timestamptz default now());
create table subscriptions (id uuid primary key default uuid_generate_v4(), organizer_id uuid not null references organizers(id), status text not null default 'INACTIVE', amount numeric(12,2) not null, starts_at timestamptz, ends_at timestamptz, created_at timestamptz default now());
create table payments (id uuid primary key default uuid_generate_v4(), user_id uuid references users(id), subscription_id uuid references subscriptions(id), amount numeric(12,2) not null check(amount>=0), currency text not null default 'GHS', provider text not null, purpose text not null, reference text unique not null, status payment_status default 'PENDING', verified_at timestamptz, metadata jsonb default '{}', created_at timestamptz default now());
create index idx_payments_user on payments(user_id); create index idx_payments_reference on payments(reference); create index idx_payments_status on payments(status);
create table service_categories (id uuid primary key default uuid_generate_v4(), name text unique not null, created_at timestamptz default now());
create table services (id uuid primary key default uuid_generate_v4(), organizer_id uuid not null references organizers(id) on delete cascade, category_id uuid references service_categories(id), name text not null, description text, price numeric(12,2) not null check(price>=0), images text[] default '{}', rating numeric(3,2) default 0, review_count int default 0, deleted_at timestamptz, created_at timestamptz default now());
create index idx_services_organizer on services(organizer_id);
create table service_alternatives (id uuid primary key default uuid_generate_v4(), service_id uuid not null references services(id) on delete cascade, name text not null, description text, price numeric(12,2) not null check(price>=0), images text[] default '{}');
create table reviews (id uuid primary key default uuid_generate_v4(), service_id uuid not null references services(id) on delete cascade, family_member_id uuid references family_members(id), rating int not null check(rating between 1 and 5), comment text, created_at timestamptz default now());
create table funeral_requests (id uuid primary key default uuid_generate_v4(), family_member_id uuid references family_members(id), organizer_id uuid not null references organizers(id), deceased_full_name text not null, funeral_date timestamptz, budget numeric(12,2), guest_breakdown jsonb not null default '{}', projected_attendance int, service_pricing_details jsonb not null default '{}', calculated_total numeric(12,2), selected_services jsonb not null default '[]', status request_status default 'PENDING', accepted_at timestamptz, submitted_in_person boolean default false, contact_name text, contact_phone text, created_at timestamptz default now());
create index idx_requests_org on funeral_requests(organizer_id,status);
create table invoices (id uuid primary key default uuid_generate_v4(), request_id uuid unique references funeral_requests(id), service_total numeric(12,2) not null, organizer_charge numeric(12,2) not null, taxes numeric(12,2) default 0, final_amount numeric(12,2) not null, status text default 'PENDING', payment_id uuid references payments(id), created_at timestamptz default now());
create table funeral_sessions (id uuid primary key default uuid_generate_v4(), request_id uuid references funeral_requests(id), organizer_id uuid not null references organizers(id), family_member_id uuid references family_members(id), illiterate_family_record_id uuid references illiterate_family_records(id), deceased_full_name text not null, session_code text unique not null, status session_status default 'PENDING', progress int default 0 check(progress between 0 and 100), started_at timestamptz, completed_at timestamptz, archived_at timestamptz, created_at timestamptz default now());
create index idx_sessions_code on funeral_sessions(session_code); create index idx_sessions_deceased on funeral_sessions using gin(to_tsvector('english', deceased_full_name));
create table session_services (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, service_id uuid references services(id), name text not null, price numeric(12,2) not null);
create table checklists (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, title text not null, completed boolean default false, due_at timestamptz);
create table timelines (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, title text not null, description text, event_at timestamptz);
create table expenses (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, title text not null, amount numeric(12,2) not null, receipt_document_id uuid, created_at timestamptz default now());
create table volunteers (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, full_name text not null, phone text, role text);
create table notes (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, author_user_id uuid references users(id), note text not null, created_at timestamptz default now());
create table donations (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, family_member_id uuid references family_members(id), type donation_type not null, donor_name text not null, amount numeric(12,2), paid boolean default false, payment_method text, momo_number text, paystack_reference text, item_name text, quantity numeric(12,2), estimated_value numeric(12,2), notes text, donor_phone text, checked_in_at timestamptz, relative_name text, relative_relationship text, approved boolean default false, approval_notes text, approved_by uuid references users(id), collector_name text, collector_identifier text, donated_at date default current_date, created_at timestamptz default now());
create index idx_donations_session on donations(session_id,type,paid,collector_name);
create index if not exists idx_donations_family_member on donations(family_member_id);
create table documents (id uuid primary key default uuid_generate_v4(), session_id uuid not null references funeral_sessions(id) on delete cascade, uploader_user_id uuid references users(id), document_type text not null, cloudinary_public_id text not null, secure_url text not null, mime_type text, size_bytes bigint, collector_name text, collector_identifier text, created_at timestamptz default now());
create table notifications (id uuid primary key default uuid_generate_v4(), user_id uuid references users(id), title text not null, body text not null, data jsonb default '{}', read_at timestamptz, created_at timestamptz default now());
create table push_tokens (id uuid primary key default uuid_generate_v4(), user_id uuid references users(id) on delete cascade, token text unique not null, platform text, created_at timestamptz default now());
create table session_summaries (id uuid primary key default uuid_generate_v4(), session_id uuid unique not null references funeral_sessions(id) on delete cascade, summary_json jsonb not null, pdf_url text, sent_at timestamptz, created_at timestamptz default now());
create table grief_support_content (id uuid primary key default uuid_generate_v4(), type text not null check(type in ('ARTICLE','VIDEO','COUNSELING','MENTAL_HEALTH','MESSAGE','COMMUNITY')), title text not null, body text, media_url text, published boolean default false, created_by uuid references users(id), created_at timestamptz default now());
create table audit_logs (id uuid primary key default uuid_generate_v4(), user_id uuid references users(id), action text not null, entity text not null, entity_id uuid, metadata jsonb default '{}', ip inet, created_at timestamptz default now());
create index idx_audit_entity on audit_logs(entity,entity_id); create index idx_audit_action on audit_logs(action); create index idx_audit_created on audit_logs(created_at);
create table otps (id uuid primary key default uuid_generate_v4(), target text not null, purpose text not null, otp_hash text not null, expires_at timestamptz not null, used_at timestamptz, created_at timestamptz default now());
create index idx_otps_target on otps(target,purpose,expires_at);

-- Supabase RLS starter. Expand policies for your exact access model.
alter table users enable row level security; alter table payments enable row level security; alter table funeral_sessions enable row level security; alter table documents enable row level security;

-- Additional columns for richer session planning and tracking
alter table funeral_sessions add column if not exists funeral_date timestamptz;
alter table funeral_sessions add column if not exists budget_final numeric(12,2);
alter table funeral_sessions add column if not exists session_meta jsonb default '{}';
